/**
 * This class is generated by jOOQ
 */
package com.mycompany.app.jooq.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.inferred.freebuilder.FreeBuilder;
/**
 * This class is generated by jOOQ.
 */
@FreeBuilder
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "absent", schema = "iob")
public interface IAbsent extends Serializable {

    class Builder extends IAbsent_Builder {}

    /**
	 * Getter for <code>iob.absent.empid</code>.
	 */
	@Column(name = "empid", nullable = false, length = 36)
	@NotNull
	@Size(max = 36)
	public String getEmpid();

	/**
	 * Getter for <code>iob.absent.absid</code>.
	 */
	@Id
	@Column(name = "absid", unique = true, nullable = false, length = 36)
	@NotNull
	@Size(max = 36)
	public String getAbsid();

	/**
	 * Getter for <code>iob.absent.absdate</code>.
	 */
	@Column(name = "absdate", nullable = false)
	@NotNull
	public Timestamp getAbsdate();

	/**
	 * Getter for <code>iob.absent.absdescription</code>.
	 */
	@Column(name = "absdescription", nullable = false, length = 1)
	@NotNull
	@Size(max = 1)
	public String getAbsdescription();

	/**
	 * Getter for <code>iob.absent.absnotes</code>.
	 */
	@Column(name = "absnotes")
	public String getAbsnotes();

	/**
	 * Getter for <code>iob.absent.absdeleted</code>.
	 */
	@Column(name = "absdeleted", nullable = false, precision = 1)
	@NotNull
	public Boolean getAbsdeleted();
}
