/**
 * This class is generated by jOOQ
 */
package com.mycompany.app.jooq.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.inferred.freebuilder.FreeBuilder;
/**
 * This class is generated by jOOQ.
 */
@FreeBuilder
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "absentlog", schema = "iob")
public interface IAbsentlog extends Serializable {

    class Builder extends IAbsentlog_Builder {}

	/**
	 * Getter for <code>iob.absentlog.empid</code>.
	 */
	@Column(name = "empid", nullable = false, length = 36)
	@NotNull
	@Size(max = 36)
	public String getEmpid();

	/**
	 * Getter for <code>iob.absentlog.absid</code>.
	 */
	@Column(name = "absid", nullable = false, length = 36)
	@NotNull
	@Size(max = 36)
	public String getAbsid();

	/**
	 * Getter for <code>iob.absentlog.logdate</code>.
	 */
	@Column(name = "logdate", nullable = false)
	@NotNull
	public Timestamp getLogdate();

	/**
	 * Getter for <code>iob.absentlog.logversionid</code>.
	 */
	@Column(name = "logversionid", nullable = false, precision = 8)
	@NotNull
	public Integer getLogversionid();
}
