/**
 * This class is generated by jOOQ
 */
package com.mycompany.app.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.inferred.freebuilder.FreeBuilder;
/**
 * This class is generated by jOOQ.
 */
@FreeBuilder
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "employee", schema = "iob")
public interface IEmployee extends Serializable {

    class Builder extends IEmployee_Builder {}

    /**
	 * Getter for <code>iob.employee.empid</code>.
	 */
	@Id
	@Column(name = "empid", unique = true, nullable = false, length = 36)
	@NotNull
	@Size(max = 36)
	public String getEmpid();

	/**
	 * Getter for <code>iob.employee.empuhnumber</code>.
	 */
	@Column(name = "empuhnumber", nullable = false, length = 17)
	@NotNull
	@Size(max = 17)
	public String getEmpuhnumber();

	/**
	 * Getter for <code>iob.employee.empfirstname</code>.
	 */
	@Column(name = "empfirstname", nullable = false, length = 40)
	@NotNull
	@Size(max = 40)
	public String getEmpfirstname();

	/**
	 * Getter for <code>iob.employee.emplastname</code>.
	 */
	@Column(name = "emplastname", nullable = false, length = 40)
	@NotNull
	@Size(max = 40)
	public String getEmplastname();

	/**
	 * Getter for <code>iob.employee.emprole</code>.
	 */
	@Column(name = "emprole", nullable = false, length = 1)
	@NotNull
	@Size(max = 1)
	public String getEmprole();

	/**
	 * Getter for <code>iob.employee.empdivision</code>.
	 */
	@Column(name = "empdivision", nullable = false, length = 40)
	@NotNull
	@Size(max = 40)
	public String getEmpdivision();

	/**
	 * Getter for <code>iob.employee.empstatus</code>.
	 */
	@Column(name = "empstatus", nullable = false, length = 1)
	@NotNull
	@Size(max = 1)
	public String getEmpstatus();
}
