/**
 * This class is generated by jOOQ
 */
package com.mycompany.app.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.inferred.freebuilder.FreeBuilder;
/**
 * This class is generated by jOOQ.
 */
@FreeBuilder
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "empmanager", schema = "iob")
public interface IEmpmanager extends Serializable {

    class Builder extends IEmpmanager_Builder {}

    /**
	 * Getter for <code>iob.empmanager.empid</code>.
	 */
	@Column(name = "empid", nullable = false, length = 36)
	@NotNull
	@Size(max = 36)
	public String getEmpid();

	/**
	 * Getter for <code>iob.empmanager.division</code>.
	 */
	@Column(name = "division", length = 40)
	@Size(max = 40)
	public String getDivision();
}
