/**
 * This class is generated by jOOQ
 */
package com.mycompany.app.jooq.tables.daos;


import com.mycompany.app.jooq.tables.Employee;
import com.mycompany.app.jooq.tables.records.EmployeeRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class EmployeeDao extends DAOImpl<EmployeeRecord, com.mycompany.app.jooq.tables.pojos.Employee, String> {

	/**
	 * Create a new EmployeeDao without any configuration
	 */
	public EmployeeDao() {
		super(Employee.EMPLOYEE, com.mycompany.app.jooq.tables.pojos.Employee.class);
	}

	/**
	 * Create a new EmployeeDao with an attached configuration
	 */
	@Autowired
	public EmployeeDao(Configuration configuration) {
		super(Employee.EMPLOYEE, com.mycompany.app.jooq.tables.pojos.Employee.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected String getId(com.mycompany.app.jooq.tables.pojos.Employee object) {
		return object.getEmpid();
	}

	/**
	 * Fetch records that have <code>empid IN (values)</code>
	 */
	public List<com.mycompany.app.jooq.tables.pojos.Employee> fetchByEmpid(String... values) {
		return fetch(Employee.EMPLOYEE.EMPID, values);
	}

	/**
	 * Fetch a unique record that has <code>empid = value</code>
	 */
	public com.mycompany.app.jooq.tables.pojos.Employee fetchOneByEmpid(String value) {
		return fetchOne(Employee.EMPLOYEE.EMPID, value);
	}

	/**
	 * Fetch records that have <code>empuhnumber IN (values)</code>
	 */
	public List<com.mycompany.app.jooq.tables.pojos.Employee> fetchByEmpuhnumber(String... values) {
		return fetch(Employee.EMPLOYEE.EMPUHNUMBER, values);
	}

	/**
	 * Fetch records that have <code>empfirstname IN (values)</code>
	 */
	public List<com.mycompany.app.jooq.tables.pojos.Employee> fetchByEmpfirstname(String... values) {
		return fetch(Employee.EMPLOYEE.EMPFIRSTNAME, values);
	}

	/**
	 * Fetch records that have <code>emplastname IN (values)</code>
	 */
	public List<com.mycompany.app.jooq.tables.pojos.Employee> fetchByEmplastname(String... values) {
		return fetch(Employee.EMPLOYEE.EMPLASTNAME, values);
	}

	/**
	 * Fetch records that have <code>emprole IN (values)</code>
	 */
	public List<com.mycompany.app.jooq.tables.pojos.Employee> fetchByEmprole(String... values) {
		return fetch(Employee.EMPLOYEE.EMPROLE, values);
	}

	/**
	 * Fetch records that have <code>empdivision IN (values)</code>
	 */
	public List<com.mycompany.app.jooq.tables.pojos.Employee> fetchByEmpdivision(String... values) {
		return fetch(Employee.EMPLOYEE.EMPDIVISION, values);
	}

	/**
	 * Fetch records that have <code>empstatus IN (values)</code>
	 */
	public List<com.mycompany.app.jooq.tables.pojos.Employee> fetchByEmpstatus(String... values) {
		return fetch(Employee.EMPLOYEE.EMPSTATUS, values);
	}
}
