/**
 * This class is generated by jOOQ
 */
package com.mycompany.app.jooq.tables;


import com.mycompany.app.jooq.Iob;
import com.mycompany.app.jooq.Keys;
import com.mycompany.app.jooq.tables.records.AbsentlogRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Absentlog extends TableImpl<AbsentlogRecord> {

	private static final long serialVersionUID = -398287437;

	/**
	 * The reference instance of <code>iob.absentlog</code>
	 */
	public static final Absentlog ABSENTLOG = new Absentlog();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AbsentlogRecord> getRecordType() {
		return AbsentlogRecord.class;
	}

	/**
	 * The column <code>iob.absentlog.empid</code>.
	 */
	public final TableField<AbsentlogRecord, String> EMPID = createField("empid", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>iob.absentlog.absid</code>.
	 */
	public final TableField<AbsentlogRecord, String> ABSID = createField("absid", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>iob.absentlog.logdate</code>.
	 */
	public final TableField<AbsentlogRecord, Timestamp> LOGDATE = createField("logdate", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>iob.absentlog.logversionid</code>.
	 */
	public final TableField<AbsentlogRecord, Integer> LOGVERSIONID = createField("logversionid", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>iob.absentlog</code> table reference
	 */
	public Absentlog() {
		this("absentlog", null);
	}

	/**
	 * Create an aliased <code>iob.absentlog</code> table reference
	 */
	public Absentlog(String alias) {
		this(alias, ABSENTLOG);
	}

	private Absentlog(String alias, Table<AbsentlogRecord> aliased) {
		this(alias, aliased, null);
	}

	private Absentlog(String alias, Table<AbsentlogRecord> aliased, Field<?>[] parameters) {
		super(alias, Iob.IOB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<AbsentlogRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<AbsentlogRecord, ?>>asList(Keys.ABSENTLOG_IBFK_1, Keys.ABSENTLOG_IBFK_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Absentlog as(String alias) {
		return new Absentlog(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Absentlog rename(String name) {
		return new Absentlog(name, null);
	}
}
