/**
 * This class is generated by jOOQ
 */
package com.mycompany.app.jooq.tables;


import com.mycompany.app.jooq.Iob;
import com.mycompany.app.jooq.Keys;
import com.mycompany.app.jooq.tables.records.EmployeeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Employee extends TableImpl<EmployeeRecord> {

	private static final long serialVersionUID = -1302060011;

	/**
	 * The reference instance of <code>iob.employee</code>
	 */
	public static final Employee EMPLOYEE = new Employee();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EmployeeRecord> getRecordType() {
		return EmployeeRecord.class;
	}

	/**
	 * The column <code>iob.employee.empid</code>.
	 */
	public final TableField<EmployeeRecord, String> EMPID = createField("empid", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>iob.employee.empuhnumber</code>.
	 */
	public final TableField<EmployeeRecord, String> EMPUHNUMBER = createField("empuhnumber", org.jooq.impl.SQLDataType.VARCHAR.length(17).nullable(false), this, "");

	/**
	 * The column <code>iob.employee.empfirstname</code>.
	 */
	public final TableField<EmployeeRecord, String> EMPFIRSTNAME = createField("empfirstname", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this, "");

	/**
	 * The column <code>iob.employee.emplastname</code>.
	 */
	public final TableField<EmployeeRecord, String> EMPLASTNAME = createField("emplastname", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this, "");

	/**
	 * The column <code>iob.employee.emprole</code>.
	 */
	public final TableField<EmployeeRecord, String> EMPROLE = createField("emprole", org.jooq.impl.SQLDataType.VARCHAR.length(1).nullable(false), this, "");

	/**
	 * The column <code>iob.employee.empdivision</code>.
	 */
	public final TableField<EmployeeRecord, String> EMPDIVISION = createField("empdivision", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this, "");

	/**
	 * The column <code>iob.employee.empstatus</code>.
	 */
	public final TableField<EmployeeRecord, String> EMPSTATUS = createField("empstatus", org.jooq.impl.SQLDataType.VARCHAR.length(1).nullable(false), this, "");

	/**
	 * Create a <code>iob.employee</code> table reference
	 */
	public Employee() {
		this("employee", null);
	}

	/**
	 * Create an aliased <code>iob.employee</code> table reference
	 */
	public Employee(String alias) {
		this(alias, EMPLOYEE);
	}

	private Employee(String alias, Table<EmployeeRecord> aliased) {
		this(alias, aliased, null);
	}

	private Employee(String alias, Table<EmployeeRecord> aliased, Field<?>[] parameters) {
		super(alias, Iob.IOB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<EmployeeRecord> getPrimaryKey() {
		return Keys.KEY_EMPLOYEE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<EmployeeRecord>> getKeys() {
		return Arrays.<UniqueKey<EmployeeRecord>>asList(Keys.KEY_EMPLOYEE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Employee as(String alias) {
		return new Employee(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Employee rename(String name) {
		return new Employee(name, null);
	}
}
