/**
 * This class is generated by jOOQ
 */
package com.mycompany.app.jooq.tables;


import com.mycompany.app.jooq.Iob;
import com.mycompany.app.jooq.Keys;
import com.mycompany.app.jooq.tables.records.EmpmanagerRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Empmanager extends TableImpl<EmpmanagerRecord> {

	private static final long serialVersionUID = 317612674;

	/**
	 * The reference instance of <code>iob.empmanager</code>
	 */
	public static final Empmanager EMPMANAGER = new Empmanager();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EmpmanagerRecord> getRecordType() {
		return EmpmanagerRecord.class;
	}

	/**
	 * The column <code>iob.empmanager.empid</code>.
	 */
	public final TableField<EmpmanagerRecord, String> EMPID = createField("empid", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>iob.empmanager.division</code>.
	 */
	public final TableField<EmpmanagerRecord, String> DIVISION = createField("division", org.jooq.impl.SQLDataType.VARCHAR.length(40), this, "");

	/**
	 * Create a <code>iob.empmanager</code> table reference
	 */
	public Empmanager() {
		this("empmanager", null);
	}

	/**
	 * Create an aliased <code>iob.empmanager</code> table reference
	 */
	public Empmanager(String alias) {
		this(alias, EMPMANAGER);
	}

	private Empmanager(String alias, Table<EmpmanagerRecord> aliased) {
		this(alias, aliased, null);
	}

	private Empmanager(String alias, Table<EmpmanagerRecord> aliased, Field<?>[] parameters) {
		super(alias, Iob.IOB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<EmpmanagerRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<EmpmanagerRecord, ?>>asList(Keys.EMPMANAGER_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Empmanager as(String alias) {
		return new Empmanager(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Empmanager rename(String name) {
		return new Empmanager(name, null);
	}
}
