/**
 * This class is generated by jOOQ
 */
package com.mycompany.app.jooq;


import com.mycompany.app.jooq.tables.Absent;
import com.mycompany.app.jooq.tables.Absentlog;
import com.mycompany.app.jooq.tables.Employee;
import com.mycompany.app.jooq.tables.Empmanager;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Iob extends SchemaImpl {

	private static final long serialVersionUID = -407716721;

	/**
	 * The reference instance of <code>iob</code>
	 */
	public static final Iob IOB = new Iob();

	/**
	 * No further instances allowed
	 */
	private Iob() {
		super("iob");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Absent.ABSENT,
			Absentlog.ABSENTLOG,
			Employee.EMPLOYEE,
			Empmanager.EMPMANAGER);
	}
}
