/**
 * This class is generated by jOOQ
 */
package com.mycompany.app.jooq;


import com.mycompany.app.jooq.tables.Absent;
import com.mycompany.app.jooq.tables.Absentlog;
import com.mycompany.app.jooq.tables.Employee;
import com.mycompany.app.jooq.tables.Empmanager;
import com.mycompany.app.jooq.tables.records.AbsentRecord;
import com.mycompany.app.jooq.tables.records.AbsentlogRecord;
import com.mycompany.app.jooq.tables.records.EmployeeRecord;
import com.mycompany.app.jooq.tables.records.EmpmanagerRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>iob</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<AbsentRecord> KEY_ABSENT_PRIMARY = UniqueKeys0.KEY_ABSENT_PRIMARY;
	public static final UniqueKey<EmployeeRecord> KEY_EMPLOYEE_PRIMARY = UniqueKeys0.KEY_EMPLOYEE_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<AbsentRecord, EmployeeRecord> ABSENT_IBFK_1 = ForeignKeys0.ABSENT_IBFK_1;
	public static final ForeignKey<AbsentlogRecord, EmployeeRecord> ABSENTLOG_IBFK_1 = ForeignKeys0.ABSENTLOG_IBFK_1;
	public static final ForeignKey<AbsentlogRecord, AbsentRecord> ABSENTLOG_IBFK_2 = ForeignKeys0.ABSENTLOG_IBFK_2;
	public static final ForeignKey<EmpmanagerRecord, EmployeeRecord> EMPMANAGER_IBFK_1 = ForeignKeys0.EMPMANAGER_IBFK_1;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<AbsentRecord> KEY_ABSENT_PRIMARY = createUniqueKey(Absent.ABSENT, Absent.ABSENT.ABSID);
		public static final UniqueKey<EmployeeRecord> KEY_EMPLOYEE_PRIMARY = createUniqueKey(Employee.EMPLOYEE, Employee.EMPLOYEE.EMPID);
	}

	private static class ForeignKeys0 extends AbstractKeys {
		public static final ForeignKey<AbsentRecord, EmployeeRecord> ABSENT_IBFK_1 = createForeignKey(com.mycompany.app.jooq.Keys.KEY_EMPLOYEE_PRIMARY, Absent.ABSENT, Absent.ABSENT.EMPID);
		public static final ForeignKey<AbsentlogRecord, EmployeeRecord> ABSENTLOG_IBFK_1 = createForeignKey(com.mycompany.app.jooq.Keys.KEY_EMPLOYEE_PRIMARY, Absentlog.ABSENTLOG, Absentlog.ABSENTLOG.EMPID);
		public static final ForeignKey<AbsentlogRecord, AbsentRecord> ABSENTLOG_IBFK_2 = createForeignKey(com.mycompany.app.jooq.Keys.KEY_ABSENT_PRIMARY, Absentlog.ABSENTLOG, Absentlog.ABSENTLOG.ABSID);
		public static final ForeignKey<EmpmanagerRecord, EmployeeRecord> EMPMANAGER_IBFK_1 = createForeignKey(com.mycompany.app.jooq.Keys.KEY_EMPLOYEE_PRIMARY, Empmanager.EMPMANAGER, Empmanager.EMPMANAGER.EMPID);
	}
}
