/**
 * This class is generated by jOOQ
 */
package com.mycompany.app.jooq;


import com.mycompany.app.jooq.tables.Absent;
import com.mycompany.app.jooq.tables.Absentlog;
import com.mycompany.app.jooq.tables.Employee;
import com.mycompany.app.jooq.tables.Empmanager;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in iob
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table iob.absent
	 */
	public static final Absent ABSENT = com.mycompany.app.jooq.tables.Absent.ABSENT;

	/**
	 * The table iob.absentlog
	 */
	public static final Absentlog ABSENTLOG = com.mycompany.app.jooq.tables.Absentlog.ABSENTLOG;

	/**
	 * The table iob.employee
	 */
	public static final Employee EMPLOYEE = com.mycompany.app.jooq.tables.Employee.EMPLOYEE;

	/**
	 * The table iob.empmanager
	 */
	public static final Empmanager EMPMANAGER = com.mycompany.app.jooq.tables.Empmanager.EMPMANAGER;
}
