// Autogenerated code. Do not modify.
package com.mycompany.app.jooq.tables.interfaces;

import javax.annotation.Generated;

/**
 * Placeholder. Create {@code IAbsentlog.Builder} and subclass this type.
 */
@Generated("org.inferred.freebuilder.processor.CodeGenerator")
abstract class IAbsentlog_Builder {}
